#!/usr/bin/env python3
"""
Execute Polymarket plans (LIVE) from plan JSON generated by signal_dryrun.py.

Safety defaults:
- Requires explicit --yes-live
- Skips entries unless status == READY_DRY_RUN and token_id exists
- Uses LIMIT BUY order with best-ask cap (or explicit --price)

Env required:
- POLY_PK                (private key, 0x...)
- POLY_FUNDER            (funder/proxy address)
Optional env:
- POLY_HOST              (default https://clob.polymarket.com)
- POLY_CHAIN_ID          (default 137)
- POLY_SIGNATURE_TYPE    (default 1)
- POLY_API_KEY / POLY_API_SECRET / POLY_API_PASSPHRASE (if already created)
"""

from __future__ import annotations

import argparse
import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional

from py_clob_client.client import ClobClient
from py_clob_client.clob_types import ApiCreds, OrderArgs


@dataclass
class ExecResult:
    index: int
    market: str
    token_id: str
    price: float
    size: float
    status: str
    note: str
    order_id: Optional[str] = None


def make_client() -> ClobClient:
    host = os.getenv("POLY_HOST", "https://clob.polymarket.com")
    chain_id = int(os.getenv("POLY_CHAIN_ID", "137"))
    signature_type = int(os.getenv("POLY_SIGNATURE_TYPE", "1"))
    key = os.getenv("POLY_PK", "").strip()
    funder = os.getenv("POLY_FUNDER", "").strip()

    if not key or not funder:
        raise SystemExit("POLY_PK dan POLY_FUNDER wajib di-set untuk live execution")

    creds = None
    if os.getenv("POLY_API_KEY") and os.getenv("POLY_API_SECRET") and os.getenv("POLY_API_PASSPHRASE"):
        creds = ApiCreds(
            api_key=os.getenv("POLY_API_KEY", "").strip(),
            api_secret=os.getenv("POLY_API_SECRET", "").strip(),
            api_passphrase=os.getenv("POLY_API_PASSPHRASE", "").strip(),
        )

    client = ClobClient(
        host,
        chain_id=chain_id,
        key=key,
        creds=creds,
        signature_type=signature_type,
        funder=funder,
    )

    # If API creds are not provided, derive and set them.
    if creds is None:
        derived = client.derive_api_key()
        client.set_api_creds(derived)
    return client


def pick_limit_price(client: ClobClient, token_id: str, explicit_price: float = 0.0) -> float:
    if explicit_price > 0:
        return explicit_price
    book = client.get_order_book(token_id)
    asks = getattr(book, "asks", None) or []
    if not asks:
        raise ValueError("Orderbook ask kosong")
    best_ask = float(asks[0].price)
    return best_ask


def load_plans(path: Path) -> List[Dict[str, Any]]:
    data = json.loads(path.read_text(encoding="utf-8"))
    plans = data.get("plans", [])
    if not isinstance(plans, list):
        raise ValueError("Format JSON plan tidak valid")
    return plans


def execute(
    plans: List[Dict[str, Any]],
    client: ClobClient,
    explicit_price: float,
    max_orders: int,
    required_status: str,
) -> List[ExecResult]:
    results: List[ExecResult] = []
    used = 0

    for i, p in enumerate(plans, 1):
        token_id = (p.get("token_id") or "").strip()
        status = p.get("status")
        market = p.get("market_slug") or f"{p.get('home')} vs {p.get('away')}"
        stake = float(p.get("stake_usd") or 0)

        allowed_statuses = {required_status} if required_status != "AUTO" else {"READY_DRY_RUN", "READY_REMOTE_EXEC"}
        if status not in allowed_statuses or not token_id:
            results.append(ExecResult(i, str(market), token_id, 0, 0, "SKIPPED", f"Status={status} (allow={sorted(allowed_statuses)}) / token kosong"))
            continue

        if max_orders > 0 and used >= max_orders:
            results.append(ExecResult(i, str(market), token_id, 0, 0, "SKIPPED", "Melebihi --max-orders"))
            continue

        try:
            price = pick_limit_price(client, token_id, explicit_price=explicit_price)
            if price <= 0 or price >= 1:
                raise ValueError(f"Price tidak valid: {price}")

            size = stake / price
            # Round size to 4 dp for safety
            size = math.floor(size * 10_000) / 10_000
            if size <= 0:
                raise ValueError("Size <= 0")

            order_args = OrderArgs(
                token_id=token_id,
                price=price,
                size=size,
                side="BUY",
            )
            signed = client.create_order(order_args)
            posted = client.post_order(signed)

            order_id = None
            if isinstance(posted, dict):
                order_id = posted.get("orderID") or posted.get("id")

            results.append(ExecResult(i, str(market), token_id, price, size, "POSTED", "Order submitted", order_id))
            used += 1
        except Exception as e:
            results.append(ExecResult(i, str(market), token_id, 0, 0, "ERROR", str(e)))

    return results


def main() -> None:
    ap = argparse.ArgumentParser(description="Execute live orders from dry-run plan JSON")
    ap.add_argument("--plan", required=True, help="Path ke plan JSON (output signal_dryrun.py)")
    ap.add_argument("--yes-live", action="store_true", help="Konfirmasi eksekusi live")
    ap.add_argument("--price", type=float, default=0.0, help="Override limit price untuk semua order")
    ap.add_argument("--max-orders", type=int, default=3, help="Batas order per eksekusi")
    ap.add_argument("--out", default="", help="Simpan hasil ke JSON")
    ap.add_argument("--plan-ready-status", default="AUTO", choices=["AUTO", "READY_DRY_RUN", "READY_REMOTE_EXEC"], help="Status plan yang diizinkan untuk dieksekusi")
    args = ap.parse_args()

    if not args.yes_live:
        raise SystemExit("Refusing to run. Tambahkan --yes-live untuk konfirmasi.")

    plans = load_plans(Path(args.plan))
    client = make_client()
    results = execute(
        plans,
        client,
        explicit_price=args.price,
        max_orders=args.max_orders,
        required_status=args.plan_ready_status,
    )

    print("=== LIVE EXEC RESULTS ===")
    for r in results:
        print(f"{r.index}. {r.market} | {r.status} | {r.note}")
        if r.status == "POSTED":
            print(f"   token={r.token_id} price={r.price:.4f} size={r.size:.4f} order_id={r.order_id}")

    if args.out:
        payload = [r.__dict__ for r in results]
        Path(args.out).write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")
        print(f"Saved: {args.out}")


if __name__ == "__main__":
    main()
